Repository SoftStackFactory/SSWHEN, pull requests merged in 2018-02, with the labels that each got.

#39 Feature/profile page feature
  src/app/app.module.ts
  src/pages/login/login.html
  src/pages/login/login.ts
  src/pages/profile/profile.html
  src/pages/profile/profile.ts
Labels: in progress

#70 Updated dashboard edit inline
  src/pages/dashboard/dashboard.html
  src/pages/dashboard/dashboard.ts
Labels: enhancement

#71 Feature/charts complete ez merge
  src/components/modal-dashboard/modal-dashboard.html
  src/components/modal-dashboard/modal-dashboard.ts
  src/models/Results.ts
  src/models/mockData/mockResults.ts
  src/pages/dashboard/dashboard.ts
  src/pages/data-table/data-table.html
  src/pages/data-table/data-table.ts
  src/pages/info-input/info-input.html
  src/pages/results/results.html
  src/pages/results/results.ts
  src/providers/mock-data/mock-data.ts
Labels: enhancement, review
